export const wordData = {
    "verbs": [
        {"kanji":"<ruby>行<rt>い<\/rt><\/ruby>く","type":"irv","eng":"go", "group": "iku"},
        {"kanji":"する","type":"irv","eng":"do, make", "group": "suru"},
        {"kanji":"<ruby>来<rt>く<\/rt><\/ruby>る","type":"irv","eng":"come"},
        {"kanji":"ある","type":"irv","eng":"have, exists, is (inanimate)"},
        {"kanji":"<ruby>問<rt>と<\/rt><\/ruby>う","type":"irv","eng":"ask, accuse"},
        {"kanji":"いる","type":"ru","eng":"exists, is (living things)"},
        {"kanji":"<ruby>始<rt>はじ<\/rt><\/ruby>める","type":"ru","eng":"begin"},
        {"kanji":"<ruby>借<rt>か<\/rt><\/ruby>りる","type":"ru","eng":"borrow, rent"},
        {"kanji":"<ruby>続<rt>つづ<\/rt><\/ruby>ける","type":"ru","eng":"continue, proceed"},
        {"kanji":"<ruby>決<rt>き<\/rt><\/ruby>める","type":"ru","eng":"decide, choose"},
        {"kanji":"<ruby>食<rt>た<\/rt><\/ruby>べる","type":"ru","eng":"eat"},
        {"kanji":"<ruby>忘<rt>わす<\/rt><\/ruby>れる","type":"ru","eng":"forget"},
        {"kanji":"<ruby>降<rt>お<\/rt><\/ruby>りる","type":"ru","eng":"get off, go down"},
        {"kanji":"<ruby>疲<rt>つか<\/rt><\/ruby>れる","type":"ru","eng":"get tired"},
        {"kanji":"<ruby>起<rt>お<\/rt><\/ruby>きる","type":"ru","eng":"get up, wake up"},
        {"kanji":"あげる","type":"ru","eng":"give"},
        {"kanji":"<ruby>出<rt>で<\/rt><\/ruby>る","type":"ru","eng":"leave, exit, appear"},
        {"kanji":"<ruby>助<rt>たす<\/rt><\/ruby>ける","type":"ru","eng":"help"},
        {"kanji":"<ruby>見<rt>み<\/rt><\/ruby>る","type":"ru","eng":"see, look"},
        {"kanji":"<ruby>開<rt>あ<\/rt><\/ruby>ける","type":"ru","eng":"open"},
        {"kanji":"<ruby>覚<rt>おぼ<\/rt><\/ruby>える","type":"ru","eng":"remember, learn"},
        {"kanji":"<ruby>寝<rt>ね<\/rt><\/ruby>る","type":"ru","eng":"sleep, go to bed"},
        {"kanji":"<ruby>閉<rt>し<\/rt><\/ruby>める","type":"ru","eng":"close"},
        {"kanji":"<ruby>着<rt>き<\/rt><\/ruby>る","type":"ru","eng":"put on, wear (shirt, jacket, etc)"},
        {"kanji":"なる","type":"u","eng":"become"},
        {"kanji":"<ruby>乗<rt>の<\/rt><\/ruby>る","type":"u","eng":"board, ride"},
        {"kanji":"<ruby>切<rt>き<\/rt><\/ruby>る","type":"u","eng":"cut"},
        {"kanji":"やる","type":"u","eng":"do, give"},
        {"kanji":"<ruby>終<rt>お<\/rt><\/ruby>わる","type":"u","eng":"end"},
        {"kanji":"<ruby>上<rt>あ<\/rt><\/ruby>がる","type":"u","eng":"go up, rise","altOkurigana":["上る"]},
        {"kanji":"<ruby>知<rt>し<\/rt><\/ruby>る","type":"u","eng":"know"},
        {"kanji":"<ruby>作<rt>つく<\/rt><\/ruby>る","type":"u","eng":"make, build"},
        {"kanji":"<ruby>帰<rt>かえ<\/rt><\/ruby>る","type":"u","eng":"return, go home"},
        {"kanji":"<ruby>取<rt>と<\/rt><\/ruby>る","type":"u","eng":"take, steal"},
        {"kanji":"<ruby>買<rt>か<\/rt><\/ruby>う","type":"u","eng":"buy"},
        {"kanji":"<ruby>笑<rt>わら<\/rt><\/ruby>う","type":"u","eng":"laugh, smile"},
        {"kanji":"<ruby>会<rt>あ<\/rt><\/ruby>う","type":"u","eng":"meet"},
        {"kanji":"<ruby>言<rt>い<\/rt><\/ruby>う","type":"u","eng":"say, utter"},
        {"kanji":"<ruby>思<rt>おも<\/rt><\/ruby>う","type":"u","eng":"think, believe"},
        {"kanji":"<ruby>使<rt>つか<\/rt><\/ruby>う","type":"u","eng":"use"},
        {"kanji":"<ruby>持<rt>も<\/rt><\/ruby>つ","type":"u","eng":"hold, have"},
        {"kanji":"<ruby>待<rt>ま<\/rt><\/ruby>つ","type":"u","eng":"wait"},
        {"kanji":"<ruby>立<rt>た<\/rt><\/ruby>つ","type":"u","eng":"stand up"},
        {"kanji":"<ruby>聞<rt>き<\/rt><\/ruby>く","type":"u","eng":"hear, listen"},
        {"kanji":"<ruby>引<rt>ひ<\/rt><\/ruby>く","type":"u","eng":"pull, tug"},
        {"kanji":"<ruby>履<rt>は<\/rt><\/ruby>く","type":"u","eng":"put on, wear (pants, skirt, shoes, etc)"},
        {"kanji":"<ruby>歩<rt>ある<\/rt><\/ruby>く","type":"u","eng":"walk"},
        {"kanji":"<ruby>書<rt>か<\/rt><\/ruby>く","type":"u","eng":"write"},
        {"kanji":"<ruby>働<rt>はたら<\/rt><\/ruby>く","type":"u","eng":"work"},
        {"kanji":"<ruby>死<rt>し<\/rt><\/ruby>ぬ","type":"u","eng":"die, pass away"},
        {"kanji":"<ruby>飲<rt>の<\/rt><\/ruby>む","type":"u","eng":"drink"},
        {"kanji":"<ruby>楽<rt>たの<\/rt><\/ruby>しむ","type":"u","eng":"enjoy, have fun"},
        {"kanji":"<ruby>進<rt>すす<\/rt><\/ruby>む","type":"u","eng":"advance, go forward"},
        {"kanji":"<ruby>住<rt>す<\/rt><\/ruby>む","type":"u","eng":"live, inhabit"},
        {"kanji":"<ruby>読<rt>よ<\/rt><\/ruby>む","type":"u","eng":"read"},
        {"kanji":"<ruby>休<rt>やす<\/rt><\/ruby>む","type":"u","eng":"rest, be absent"},
        {"kanji":"<ruby>遊<rt>あそ<\/rt><\/ruby>ぶ","type":"u","eng":"play, have a good time"},
        {"kanji":"<ruby>学<rt>まな<\/rt><\/ruby>ぶ","type":"u","eng":"study, learn"},
        {"kanji":"<ruby>選<rt>えら<\/rt><\/ruby>ぶ","type":"u","eng":"choose, select"},
        {"kanji":"<ruby>返<rt>かえ<\/rt><\/ruby>す","type":"u","eng":"return (something), put back"},
        {"kanji":"<ruby>押<rt>お<\/rt><\/ruby>す","type":"u","eng":"push, press"},
        {"kanji":"<ruby>治<rt>なお<\/rt><\/ruby>す","type":"u","eng":"cure, repair"},
        {"kanji":"<ruby>話<rt>はな<\/rt><\/ruby>す","type":"u","eng":"talk, speak"},
        {"kanji":"<ruby>探<rt>さが<\/rt><\/ruby>す","type":"u","eng":"search, look for"},
        {"kanji":"<ruby>貸<rt>か<\/rt><\/ruby>す","type":"u","eng":"lend, loan"},
        {"kanji":"<ruby>泳<rt>およ<\/rt><\/ruby>ぐ","type":"u","eng":"swim"},
        {"kanji":"<ruby>脱<rt>ぬ<\/rt><\/ruby>ぐ","type":"u","eng":"take off clothes, undress"},
        {"kanji":"<ruby>急<rt>いそ<\/rt><\/ruby>ぐ","type":"u","eng":"hurry"},
        {"kanji":"<ruby>稼<rt>かせ<\/rt><\/ruby>ぐ","type":"u","eng":"earn income, make money"},
        {"kanji":"<ruby>寛<rt>くつろ<\/rt><\/ruby>ぐ","type":"u","eng":"relax, feel at home"},
        {"kanji":"<ruby>繋<rt>つな<\/rt><\/ruby>ぐ","type":"u","eng":"connect, link together"},
        {"kanji":"<ruby>分<rt>わ<\/rt><\/ruby>かる","type":"u","eng":"understand"},
        {"kanji":"<ruby>勉<rt>べん<\/rt><\/ruby><ruby>強<rt>きょう<\/rt><\/ruby>する","type":"irv","eng":"study", "group": "suru"},
        {"kanji":"<ruby>受<rt>う<\/rt><\/ruby>け<ruby>持<rt>も<\/rt><\/ruby>つ","type":"u","eng":"take charge of"},
        {"kanji":"<ruby>持<rt>も<\/rt><\/ruby>って<ruby>行<rt>い<\/rt><\/ruby>く","type":"irv","eng":"take, carry away", "group": "iku"},
        {"kanji":"<ruby>食<rt>た<\/rt><\/ruby>べ<ruby>歩<rt>ある<\/rt><\/ruby>く","type":"u","eng":"try food at various restaurants"}
    ],
    "adjectives": [
        {"kanji":"いい","type":"ira","eng":"good"},
        {"kanji":"かっこいい","type":"ira","eng":"cool, handsome"},
        {"kanji":"<ruby>赤<rt>あか<\/rt><\/ruby>い","type":"i","eng":"red"},
        {"kanji":"<ruby>新<rt>あたら<\/rt><\/ruby>しい","type":"i","eng":"new"},
        {"kanji":"<ruby>暑<rt>あつ<\/rt><\/ruby>い","type":"i","eng":"hot (weather)"},
        {"kanji":"<ruby>危<rt>あぶ<\/rt><\/ruby>ない","type":"i","eng":"dangerous"},
        {"kanji":"<ruby>美<rt>お<\/rt><\/ruby><ruby>味<rt>い<\/rt><\/ruby>しい","type":"i","eng":"delicious"},
        {"kanji":"<ruby>大<rt>おお<\/rt><\/ruby>きい","type":"i","eng":"big"},
        {"kanji":"<ruby>遅<rt>おそ<\/rt><\/ruby>い","type":"i","eng":"late, slow"},
        {"kanji":"<ruby>面<rt>おも<\/rt><\/ruby><ruby>白<rt>しろ<\/rt><\/ruby>い","type":"i","eng":"interesting, funny"},
        {"kanji":"<ruby>可<rt>か<\/rt><\/ruby><ruby>愛<rt>わい<\/rt><\/ruby>い","type":"i","eng":"cute, pretty"},
        {"kanji":"<ruby>寒<rt>さむ<\/rt><\/ruby>い","type":"i","eng":"cold (weather)"},
        {"kanji":"<ruby>高<rt>たか<\/rt><\/ruby>い","type":"i","eng":"high, expensive"},
        {"kanji":"<ruby>楽<rt>たの<\/rt><\/ruby>しい","type":"i","eng":"fun, pleasant"},
        {"kanji":"<ruby>小<rt>ちい<\/rt><\/ruby>さい","type":"i","eng":"small"},
        {"kanji":"<ruby>詰<rt>つま<\/rt><\/ruby>らない","type":"i","eng":"uninteresting, boring","altOkurigana":["詰まらない"]},
        {"kanji":"<ruby>速<rt>はや<\/rt><\/ruby>い","type":"i","eng":"fast, quick"},
        {"kanji":"<ruby>古<rt>ふる<\/rt><\/ruby>い","type":"i","eng":"old (thing)"},
        {"kanji":"<ruby>欲<rt>ほ<\/rt><\/ruby>しい","type":"i","eng":"wanted, desired"},
        {"kanji":"<ruby>難<rt>むずか<\/rt><\/ruby>しい","type":"i","eng":"difficult"},
        {"kanji":"<ruby>安<rt>やす<\/rt><\/ruby>い","type":"i","eng":"cheap"},
        {"kanji":"<ruby>好<rt>す<\/rt><\/ruby>き","type":"na","eng":"like"},
        {"kanji":"<ruby>有<rt>ゆう<\/rt><\/ruby><ruby>名<rt>めい<\/rt><\/ruby>","type":"na","eng":"famous"},
        {"kanji":"きれい","type":"na","eng":"beautiful, tidy"},
        {"kanji":"<ruby>嫌<rt>きら<\/rt><\/ruby>い","type":"na","eng":"dislike"},
        {"kanji":"<ruby>静<rt>しず<\/rt><\/ruby>か","type":"na","eng":"quiet"},
        {"kanji":"<ruby>元<rt>げん<\/rt><\/ruby><ruby>気<rt>き<\/rt><\/ruby>","type":"na","eng":"healthy"},
        {"kanji":"<ruby>色<rt>いろ<\/rt><\/ruby><ruby>々<rt>いろ<\/rt><\/ruby>","type":"na","eng":"various"},
        {"kanji":"<ruby>心<rt>しん<\/rt><\/ruby><ruby>配<rt>ぱい<\/rt><\/ruby>","type":"na","eng":"worry, care"},
        {"kanji":"<ruby>嫌<rt>いや<\/rt><\/ruby>","type":"na","eng":"unpleasant, detestable"},
        {"kanji":"<ruby>十<rt>じゅう<\/rt><\/ruby><ruby>分<rt>ぶん<\/rt><\/ruby>","type":"na","eng":"sufficient"},
        {"kanji":"<ruby>立<rt>りっ<\/rt><\/ruby><ruby>派<rt>ぱ<\/rt><\/ruby>","type":"na","eng":"excellent, splendid"},
        {"kanji":"<ruby>同<rt>おな<\/rt><\/ruby>じ","type":"na","eng":"same, alike"},
        {"kanji":"<ruby>大<rt>だい<\/rt><\/ruby><ruby>丈<rt>じょう<\/rt><\/ruby><ruby>夫<rt>ぶ<\/rt><\/ruby>","type":"na","eng":"okay, safe"},
        {"kanji":"<ruby>真<rt>ま<\/rt><\/ruby>っ<ruby>直<rt>す<\/rt><\/ruby>ぐ","type":"na","eng":"straight, direct","altOkurigana":["真直ぐ","真すぐ","真っすぐ"]},
        {"kanji":"<ruby>下<rt>へ<\/rt><\/ruby><ruby>手<rt>た<\/rt><\/ruby>","type":"na","eng":"unskilled"},
        {"kanji":"<ruby>簡<rt>かん<\/rt><\/ruby><ruby>単<rt>たん<\/rt><\/ruby>","type":"na","eng":"simple, easy"},
        {"kanji":"<ruby>楽<rt>らく<\/rt><\/ruby>","type":"na","eng":"comfortable, easy"},
        {"kanji":"<ruby>残<rt>ざん<\/rt><\/ruby><ruby>念<rt>ねん<\/rt><\/ruby>","type":"na","eng":"unfortunate, disappointing"},
        {"kanji":"<ruby>必<rt>ひつ<\/rt><\/ruby><ruby>要<rt>よう<\/rt><\/ruby>","type":"na","eng":"necessary"}
    ]
}